- name: copy mongodb yum repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update mongodb listen adress
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download App Content & Extract it
  ansible.builtin.unarchive:
    src: https://github.com/sunivibha/{{ COMPONENT }}/archive/refs/heads/main.zip
    dest: "/tmp"
    remote_src: yes

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users




