- name: Create All RoboShop Parameters
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: "us-east-1"
      loop:
        - {name: "param.dev.catalogue.MONGO", value: "true"}
        - {name: "param.dev.catalogue.MONGO_ENDPOINT", value: "dev-mongodb.suvi88.online"}
        - {name: "param.dev.catalogue.MONGO_URL", value: "mongodb://dev-mongodb.suvi88.online:27017/catalogue"}
        - {name: "param.dev.frontend.CATALOGUE_URL", value: "http://dev-catalogue.suvi88.online:8080/"}
        - {name: "param.dev.frontend.USER_URL", value: "http://dev-user.suvi88.online:8080/"}
        - {name: "param.dev.frontend.CART_URL", value: "http://dev-cart.suvi88.online:8080/"}
        - {name: "param.dev.frontend.SHIPPING_URL", value: "http://dev-shipping.suvi88.online:8080/"}
        - {name: "param.dev.frontend.PAYMENT_URL", value: "http://dev-payment.suvi88.online:8080/"}
        - { name: "param.dev.user.MONGO", value: "true" }
        - { name: "param.dev.user.MONGO_ENDPOINT", value: "dev-mongodb.suvi88.online"}
        - { name: "param.dev.user.MONGO_URL", value: "mongodb://dev-mongodb.suvi88.online:27017/users"}
        - { name: "param.dev.user.REDIS_HOST", value: "dev-redis.suvi88.online"}
        - { name: "param.dev.cart.REDIS_HOST", value: "dev-redis.suvi88.online"}
        - { name: "param.dev.cart.CATALOGUE_HOST", value: "dev-catalogue.suvi88.online"}
        - { name: "param.dev.cart.CATALOGUE_PORT", value: "8080"}
        - { name: "param.dev.mysql.ROOT_PASSWORD", value: "RoboShop@1"}
        - { name: "param.dev.shipping.DB_HOST", value: "dev-mysql.suvi88.online"}
        - { name: "param.dev.shipping.CART_ENDPOINT", value: "dev-cart.suvi88.online:8080"}
        - { name: "param.dev.payment.USER_HOST", value: "dev-user.suvi88.online"}
        - { name: "param.dev.payment.CART_HOST", value: "dev-cart.suvi88.online"}
        - { name: "param.dev.payment.AMQP_HOST", value: "dev-rabbitmq.suvi88.online"}
        - { name: "param.dev.payment.AMQP_USER", value: "roboshop"}
        - { name: "param.dev.payment.AMQP_PASS", value: "roboshop123"}
        - { name: "param.dev.rabbitmq.AMQP_PASS", value: "roboshop123"}
        - { name: "param.dev.rabbitmq.AMQP_USER", value: "roboshop"}


