- name: demo
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
   - name: print url
     ansible.builtin.debug:
       msg: url = {{ url }}

- name: demo
  hosts: localhost
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: url = {{ url }}
      vars:
        url: play.example.com