- name: Get root Password from Parameter store
  ansible.builtin.set_fact:
    ROOT_PASSWORD: "{{ lookup('aws_ssm', 'param.{{ENV}}.mysql.ROOT_PASSWORD', region='us-east-1' ) }}"

- name: Copy MySQL Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL 8 Version repo
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install MySQL Server
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - python3-PyMySQL
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes


