- name: setup prometheus server config
  when: PROMSERVER is defined
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: server

- name: setup prometheus node config
  when: promnode is defined
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node

