- name: Copy Record Rules
  ansible.builtin.template:
    src: record_rules.yml
    dest: /opt/prometheus/record_rules.yml

- name: Copy Alert Rules
  ansible.builtin.template:
    src: alert_rules.yml
    dest: /opt/prometheus/alert_rules.yml

- name: copy prometheus config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Check Prometheus Service is running
  ansible.builtin.shell: netstat -lntp | grep 9090




