- name: add roboshop application user
  when: APP_USER is defined
  ansible.builtin.user:
    name: '{{ APP_USER }}'


- name: Remove Previous Version of App
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent


- name: Download App Content & Extract it
  ansible.builtin.unarchive:
    src: https://github.com/sunivibha/{{ COMPONENT }}/archive/refs/heads/main.zip
    dest: "/tmp"
    remote_src: yes

- name: copy Extracted App Content to App location
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/
    dest: "{{ APP_LOC }}"
    remote_src: yes