groups:
  - name: custom
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          project: roboshop
        annotations:
          summary: InstanceDown
          description: InstanceDown
{% for componet in APPLICATION_LIST %}
      - alert: Application Down - {{component.name}}
        expr: node_systemd_unit_state{name="{{component.serviceName}}.service",state="active"} == 0
        labels:
          severity: warnibg
          project: roboshop
        annotations:
          summary: Application Down - {{component.name}}
          description: InstanceDown - {{component.name}}
{% endfor %}
